Fix github url strings (org edx -> openedx)
edx/openedx-census pull request #13
Opened 2022-09-07 03:11 UTC by sarina

## This PR was autogenerated

This pr replaces the old GitHub organization, github.com/edx, with the new GitHub organization, github.com/openedx.

Tagging @openedx/tcril-engineering for review, but others are welcome to provide review.

Ref: https://github.com/openedx/tcril-engineering/issues/42

2022-09-07 13:28 UTC, nedbat approved these changes

2022-09-07 13:33 UTC, nedbat commented
Oops, there's an issue with files generated by edx-lint: https://github.com/openedx/openedx-webhooks/pull/198/files#r964846683

2022-09-07 13:33 UTC, nedbat requested changes
.editorconfig needs to be regenerated using edx-lint so that the checksum at the end is correct.

2022-09-11 21:15 UTC, sarina commented
Something is messed up with this branch so I'm closing this PR and re-doing it.

2022-09-11 21:15 UTC, closed without merging